version: "3"

services:
  db:
    container_name: vagas-db
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=vagas
      - MYSQL_USER=vagas 
      - MYSQL_PASSWORD=vagas